packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
patchedDependencies:
  react-native-css-interop@0.2.6: patches/react-native-css-interop@0.2.6.patch
