'use client';
import { useEffect, useMemo } from 'react';
import Link from 'next/link';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, CalendarPlus, CarFront, CircleAlert, Clock3, MapPin, MessageCircle, Plus, ShieldCheck, Users, WalletCards } from 'lucide-react';
import { SocketEvents } from '@repo/shared';
import apiClient from '@/lib/api-client';
import { useAuth } from '@/components/providers/auth-provider';
import { useSocket } from '@/components/providers/socket-provider';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function DriverDashboardPage() {
  const { user, loading } = useAuth(); const { socket } = useSocket(); const client = useQueryClient(); const enabled = !!user;
  const rides = useQuery({ queryKey: ['driver-dashboard', 'rides'], enabled, queryFn: async () => { const r = await apiClient.get('/rides/mine'); return (r.data?.rides ?? r.data ?? []) as any[]; } });
  const bookings = useQuery({ queryKey: ['driver-dashboard', 'bookings'], enabled, queryFn: async () => { const r = await apiClient.get('/bookings/driver'); return (r.data?.bookings ?? r.data ?? []) as any[]; } });
  const vehicles = useQuery({ queryKey: ['driver-dashboard', 'vehicles'], enabled, queryFn: async () => { const r = await apiClient.get('/vehicles'); return (r.data?.vehicles ?? r.data ?? []) as any[]; } });
  const wallet = useQuery({ queryKey: ['driver-dashboard', 'wallet'], enabled, queryFn: async () => { const r = await apiClient.get('/payments/wallet'); return r.data?.wallet ?? r.data?.data?.wallet ?? r.data; } });
  useEffect(() => { if (!socket) return; const refresh = () => client.invalidateQueries({ queryKey: ['driver-dashboard'] }); const events = [SocketEvents.RIDE_CREATED, SocketEvents.RIDE_UPDATED, SocketEvents.RIDE_STATUS_UPDATED, SocketEvents.BOOKING_NEW_REQUEST, SocketEvents.BOOKING_CONFIRMED, SocketEvents.BOOKING_REJECTED, SocketEvents.BOOKING_CANCELLED, SocketEvents.TRIP_UPDATED]; events.forEach(e => socket.on(e, refresh)); return () => events.forEach(e => socket.off(e, refresh)); }, [client, socket]);
  const now = new Date(); const today = (rides.data ?? []).filter(ride => new Date(ride.departureTime).toDateString() === now.toDateString()); const pending = (bookings.data ?? []).filter(item => item.status === 'PENDING');
  const upcoming = useMemo(() => (rides.data ?? []).filter(ride => ['SCHEDULED', 'FULL'].includes(ride.status) && new Date(ride.departureTime).getTime() >= Date.now()).sort((a,b) => +new Date(a.departureTime) - +new Date(b.departureTime))[0], [rides.data]);
  const passengers = today.reduce((sum, ride) => sum + (ride.bookedSeats ?? Math.max(0, (ride.totalSeats ?? 0) - (ride.availableSeats ?? 0))), 0); const initial = loading || [rides, bookings, vehicles, wallet].some(q => q.isLoading);
  if (initial) return <DashboardSkeleton />;
  return <main className="min-h-[calc(100dvh-3rem)] bg-background"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:py-12">
    <header className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-emerald-700">Không gian tài xế</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Xin chào, {user?.firstName || 'tài xế'}</h1><p className="mt-2 text-sm text-muted-foreground">Tổng quan nhanh để sẵn sàng cho hành trình hôm nay.</p></div><Link href="/rides/post"><Button className="min-h-11 gap-2 bg-emerald-700 hover:bg-emerald-800"><Plus className="h-4 w-4" />Đăng chuyến</Button></Link></header>
    {!user?.isDriverVerified && <Banner icon={ShieldCheck} title="Hoàn tất xác thực tài xế" text="Bạn cần KYC được duyệt trước khi nhận cuốc Ride-Hailing." href="/profile/driver-verification" label="Xác thực ngay" />}
    {vehicles.data?.length === 0 && <Banner icon={CarFront} title="Bạn chưa có phương tiện" text="Thêm phương tiện để đăng chuyến và nhận hành khách." href="/profile/vehicles" label="Thêm phương tiện" />}
    {[rides, bookings, vehicles, wallet].some(q => q.isError) && <div role="alert" className="mt-6 flex items-center gap-3 rounded-xl bg-destructive/10 p-4 text-sm"><CircleAlert className="h-5 w-5 text-destructive" />Một số dữ liệu chưa tải được. Các khu vực còn lại vẫn có thể sử dụng.</div>}
    <section aria-label="Tóm tắt hôm nay" className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Chuyến hôm nay" value={today.length} icon={CarFront} /><Stat label="Hành khách" value={passengers} icon={Users} /><Stat label="Yêu cầu chờ" value={pending.length} icon={Clock3} /><Stat label="Thu nhập khả dụng" value={`${Math.round(wallet.data?.driverEarnings ?? 0).toLocaleString('vi-VN')}đ`} icon={WalletCards} /></section>
    <section className="mt-8"><h2 className="text-lg font-semibold">Thao tác nhanh</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Quick href="/rides/post" icon={Plus} label="Đăng chuyến" /><Quick href="/rides/post?schedule=true" icon={CalendarPlus} label="Lên lịch" /><Quick href="/booking-requests" icon={Users} label="Yêu cầu đặt chỗ" badge={pending.length} /><Quick href="/profile/wallet" icon={WalletCards} label="Ví / Thu nhập" /></div></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Chuyến sắp tới</h2><Link href="/my-rides" className="text-sm font-medium text-primary hover:underline">Xem tất cả</Link></div>{upcoming ? <Upcoming ride={upcoming} /> : <Empty title="Chưa có chuyến sắp tới" text="Lên lịch một hành trình để bắt đầu nhận đặt chỗ." href="/rides/post" label="Lên lịch chuyến" />}</section>
    <section><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Yêu cầu mới</h2><Link href="/booking-requests" className="text-sm font-medium text-primary hover:underline">Xem tất cả</Link></div><div className="mt-4 overflow-hidden rounded-xl border bg-card">{pending.length ? pending.slice(0,3).map(item => <Link key={item.id} href={`/bookings/${item.id}`} className="flex min-h-20 items-center gap-3 border-b p-4 last:border-0 hover:bg-muted/50"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-amber-100 text-amber-700"><Users className="h-4 w-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{[item.passenger?.firstName, item.passenger?.lastName].filter(Boolean).join(' ') || 'Hành khách'}</strong><span className="text-xs text-muted-foreground">{item.seats ?? 1} ghế · {Math.round(item.totalPrice ?? 0).toLocaleString('vi-VN')}đ</span></span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>) : <div className="p-8 text-center text-sm text-muted-foreground">Chưa có yêu cầu chờ xử lý.</div>}</div></section></div>
  </div></main>;
}
function Stat({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof CarFront }) { return <div className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className="h-5 w-5 text-emerald-700" /></div><p className="mt-3 text-2xl font-semibold tabular-nums">{value}</p></div>; }
function Quick({ href, icon: Icon, label, badge }: { href: string; icon: typeof Plus; label: string; badge?: number }) { return <Link href={href} className="group flex min-h-20 items-center gap-3 rounded-xl border bg-card p-4 transition-colors hover:border-emerald-700/40 hover:bg-emerald-50/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5" /></span><strong className="text-sm">{label}</strong>{!!badge && <Badge className="ml-auto">{badge}</Badge>}<ArrowRight className="ml-auto h-4 w-4 text-muted-foreground group-hover:text-emerald-700" /></Link>; }
function Banner({ icon: Icon, title, text, href, label }: { icon: typeof ShieldCheck; title: string; text: string; href: string; label: string }) { return <div className="mt-6 flex flex-col gap-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-950 sm:flex-row sm:items-center"><Icon className="h-6 w-6 shrink-0 text-amber-700" /><div className="flex-1"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-amber-900/75">{text}</p></div><Link href={href}><Button variant="outline" className="min-h-11 border-amber-300 bg-white">{label}</Button></Link></div>; }
function Upcoming({ ride }: { ride: any }) { const booked = ride.bookedSeats ?? Math.max(0, (ride.totalSeats ?? 0) - (ride.availableSeats ?? 0)); return <article className="mt-4 rounded-xl border bg-card p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium text-emerald-700">{new Date(ride.departureTime).toLocaleString('vi-VN')}</p><h3 className="mt-1 font-semibold">Chuyến gần nhất</h3></div><Badge variant="secondary">{ride.status === 'FULL' ? 'Đã đủ chỗ' : 'Đã lên lịch'}</Badge></div><div className="mt-5 grid gap-3 text-sm"><p className="flex gap-2"><MapPin className="h-4 w-4 shrink-0 text-emerald-700" />{ride.origin}</p><p className="flex gap-2"><MapPin className="h-4 w-4 shrink-0 text-destructive" />{ride.destination}</p></div><div className="mt-5 flex flex-wrap gap-2 text-xs text-muted-foreground"><span className="rounded-md bg-muted px-2.5 py-2">{booked} ghế đã đặt · {ride.availableSeats ?? 0} ghế còn</span>{ride.vehicle && <span className="rounded-md bg-muted px-2.5 py-2">{ride.vehicle.licensePlate}</span>}</div><Link href={`/my-rides/${ride.id}`}><Button className="mt-5 min-h-11 gap-2">Xem chi tiết<ArrowRight className="h-4 w-4" /></Button></Link></article>; }
function Empty({ title, text, href, label }: { title: string; text: string; href: string; label: string }) { return <div className="mt-4 flex min-h-64 flex-col items-center justify-center rounded-xl border border-dashed bg-card p-8 text-center"><CalendarPlus className="h-8 w-8 text-muted-foreground" /><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p><Link href={href}><Button className="mt-5 min-h-11">{label}</Button></Link></div>; }
function DashboardSkeleton() { return <div className="mx-auto max-w-7xl px-4 py-10"><div className="h-9 w-72 animate-pulse rounded bg-muted" /><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[0,1,2,3].map(i => <div key={i} className="h-28 animate-pulse rounded-xl bg-muted" />)}</div><div className="mt-8 h-80 animate-pulse rounded-xl bg-muted" /></div>; }
