'use client';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useQueries, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, ArrowLeft, CarFront, Loader2, MessageCircle, RefreshCw, Search, Send, UserRound } from 'lucide-react';
import { SocketEvents } from '@repo/shared';
import { useAuth } from '@/components/providers/auth-provider';
import { useRoleMode } from '@/components/providers/role-mode-provider';
import { useSocket } from '@/components/providers/socket-provider';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { ChatMessage, chatService, Conversation } from '@/services/chat-service';

export function MessagesWorkspace({ conversationId }: { conversationId?: string }) {
  const { user } = useAuth(); const { mode } = useRoleMode(); const { socket, isConnected } = useSocket(); const client = useQueryClient(); const [search, setSearch] = useState('');
  const conversations = useQuery({ queryKey: ['conversations', mode], queryFn: () => chatService.conversations(mode), enabled: !!user });
  const histories = useQueries({ queries: (conversations.data ?? []).map((item) => ({ queryKey: ['chat', item.rideId, item.otherUserId], queryFn: () => chatService.history(item.rideId, item.otherUserId), staleTime: 20_000 })) });
  const selected = conversations.data?.find((item) => item.id === conversationId);
  const filtered = useMemo(() => (conversations.data ?? []).filter((item) => `${item.otherUserName} ${item.route}`.toLowerCase().includes(search.toLowerCase())), [conversations.data, search]);
  useEffect(() => { if (!socket || !user) return; const receive = (message: ChatMessage) => { const otherUserId = message.senderId === user.id ? message.receiverId : message.senderId; const key = ['chat', message.rideId, otherUserId] as const; client.setQueryData<ChatMessage[]>(key, (current) => { const messages = Array.isArray(current) ? current : []; return messages.some(item => item.id === message.id) ? messages : [...messages, message]; }); }; socket.on(SocketEvents.CHAT_RECEIVE, receive); return () => { socket.off(SocketEvents.CHAT_RECEIVE, receive); }; }, [client, socket, user]);
  return <main className="h-[calc(100dvh-3rem-80px)] min-h-[560px] bg-background lg:h-[calc(100dvh-3rem)]"><div className="mx-auto flex h-full max-w-7xl overflow-hidden border-x bg-card">
    <aside className={cn('w-full shrink-0 border-r md:w-[340px] lg:w-[380px]', conversationId && 'hidden md:block')}><div className="border-b p-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Tin nhắn</h1><p className="mt-1 text-xs text-muted-foreground">{isConnected ? 'Đang cập nhật thời gian thực' : 'Đang kết nối lại…'}</p></div><MessageCircle className="h-6 w-6 text-primary" /></div><div className="relative mt-4"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Tìm cuộc trò chuyện" value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm người hoặc chuyến đi" className="h-11 pl-9" /></div></div>
    <div className="h-[calc(100%-129px)] overflow-y-auto">{conversations.isLoading ? [0,1,2].map(i => <div key={i} className="m-3 h-20 animate-pulse rounded-lg bg-muted" />) : conversations.isError ? <ListState title="Không thể tải hội thoại" icon={RefreshCw} /> : !filtered.length ? <ListState title="Chưa có cuộc trò chuyện" icon={MessageCircle} /> : filtered.map((item) => { const index = conversations.data?.findIndex(c => c.id === item.id) ?? -1; const history = histories[index]?.data ?? []; const latest = history.at(-1); const unread = history.filter(m => !m.isRead && m.receiverId === user?.id).length; return <Link key={item.id} href={`/messages/${item.id}`} className={cn('flex min-h-24 gap-3 border-b p-4 transition-colors hover:bg-muted/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring', conversationId === item.id && 'bg-primary/[0.06]')}><Avatar item={item} /><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="truncate text-sm">{item.otherUserName}</strong>{latest && <time className="shrink-0 text-[11px] text-muted-foreground">{new Date(latest.createdAt).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}</time>}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{latest?.content ?? item.route}</span><span className="mt-1 flex items-center gap-1 truncate text-[11px] text-muted-foreground"><CarFront className="h-3 w-3" />{item.route}</span></span>{unread > 0 && <span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-primary px-1 text-[10px] font-bold text-primary-foreground">{unread}</span>}</Link>; })}</div></aside>
    <section className={cn('min-w-0 flex-1', !conversationId && 'hidden md:flex')}>{selected && user ? <ConversationPanel conversation={selected} currentUserId={user.id} /> : conversationId && !conversations.isLoading ? <EmptyConversation title="Không tìm thấy hội thoại" /> : <EmptyConversation title="Chọn một cuộc trò chuyện" />}</section>
  </div></main>;
}
function ConversationPanel({ conversation, currentUserId }: { conversation: Conversation; currentUserId: string }) {
  const { socket, isConnected } = useSocket(); const client = useQueryClient(); const [text, setText] = useState(''); const scroll = useRef<HTMLDivElement>(null);
  const query = useQuery({ queryKey: ['chat', conversation.rideId, conversation.otherUserId], queryFn: () => chatService.history(conversation.rideId, conversation.otherUserId) }); const messages = query.data ?? [];
  useEffect(() => { void chatService.markRead(conversation.rideId, conversation.otherUserId).catch(() => undefined); }, [conversation.otherUserId, conversation.rideId, messages.length]);
  useEffect(() => { scroll.current?.scrollTo({ top: scroll.current.scrollHeight, behavior: messages.length > 1 ? 'smooth' : 'auto' }); }, [messages.length]);
  useEffect(() => { if (!socket) return; const sent = (message: ChatMessage) => { if (message.rideId !== conversation.rideId || message.receiverId !== conversation.otherUserId) return; client.setQueryData<ChatMessage[]>(['chat', conversation.rideId, conversation.otherUserId], (current) => { const messages = Array.isArray(current) ? current : []; return [...messages.filter(item => !item.pending && item.id !== message.id), message]; }); }; const failed = () => client.setQueryData<ChatMessage[]>(['chat', conversation.rideId, conversation.otherUserId], (current) => { const messages = Array.isArray(current) ? current : []; return messages.map(item => item.pending ? { ...item, pending: false, failed: true } : item); }); socket.on(SocketEvents.CHAT_SENT, sent); socket.on('chat:error', failed); return () => { socket.off(SocketEvents.CHAT_SENT, sent); socket.off('chat:error', failed); }; }, [client, conversation, socket]);
  const send = (event: FormEvent) => { event.preventDefault(); const content = text.trim(); if (!content || !socket || !isConnected) return; const optimistic: ChatMessage = { id: `pending-${Date.now()}`, rideId: conversation.rideId, senderId: currentUserId, receiverId: conversation.otherUserId, content, isRead: false, createdAt: new Date().toISOString(), pending: true }; client.setQueryData<ChatMessage[]>(['chat', conversation.rideId, conversation.otherUserId], (current) => [...(Array.isArray(current) ? current : []), optimistic]); socket.emit('chat:send', { rideId: conversation.rideId, receiverId: conversation.otherUserId, content }); setText(''); };
  return <div className="flex h-full w-full flex-col"><header className="flex min-h-[76px] items-center gap-3 border-b px-4 sm:px-6"><Link href="/messages" className="flex h-11 w-11 items-center justify-center rounded-lg hover:bg-muted md:hidden" aria-label="Quay lại danh sách"><ArrowLeft className="h-5 w-5" /></Link><Avatar item={conversation} /><div className="min-w-0 flex-1"><h2 className="truncate font-semibold">{conversation.otherUserName}</h2><p className="truncate text-xs text-muted-foreground">{conversation.route}</p></div></header>
  <div ref={scroll} className="flex-1 overflow-y-auto bg-muted/20 p-4 sm:p-6">{query.isLoading ? <div className="flex h-full items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div> : query.isError ? <EmptyConversation title="Không thể tải tin nhắn" /> : !messages.length ? <EmptyConversation title="Hãy bắt đầu cuộc trò chuyện" /> : <div className="space-y-3">{messages.map(msg => { const mine = msg.senderId === currentUserId; return <div key={msg.id} className={cn('flex', mine ? 'justify-end' : 'justify-start')}><div className={cn('max-w-[78%] rounded-2xl px-4 py-2.5 text-sm leading-5', mine ? 'rounded-br-md bg-primary text-primary-foreground' : 'rounded-bl-md border bg-card')}><p>{msg.content}</p><span className={cn('mt-1 flex items-center justify-end gap-1 text-[10px]', mine ? 'text-primary-foreground/70' : 'text-muted-foreground')}>{new Date(msg.createdAt).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}{msg.pending && ' · Đang gửi'}{msg.failed && <><AlertCircle className="h-3 w-3" /> Gửi lỗi</>}</span></div></div>; })}</div>}</div>
  <form onSubmit={send} className="border-t bg-card p-3 sm:p-4"><div className="mx-auto flex max-w-3xl items-end gap-2"><label htmlFor="message" className="sr-only">Tin nhắn</label><textarea id="message" rows={1} value={text} onChange={e => setText(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} placeholder={isConnected ? 'Nhập tin nhắn…' : 'Đang kết nối lại…'} disabled={!isConnected} className="min-h-11 max-h-32 flex-1 resize-y rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-ring disabled:opacity-50" /><Button type="submit" size="icon" className="h-11 w-11 shrink-0" disabled={!text.trim() || !isConnected} aria-label="Gửi tin nhắn"><Send className="h-4 w-4" /></Button></div></form></div>;
}
function Avatar({ item }: { item: Conversation }) { return <span className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-primary">{item.avatarUrl ? <img src={item.avatarUrl} alt="" className="h-full w-full object-cover" /> : <UserRound className="h-5 w-5" />}</span>; }
function EmptyConversation({ title }: { title: string }) { return <div className="flex h-full w-full flex-col items-center justify-center p-8 text-center"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-muted"><MessageCircle className="h-7 w-7 text-muted-foreground" /></span><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">Tin nhắn được bảo vệ trong ngữ cảnh chuyến đi và cập nhật theo thời gian thực.</p></div>; }
function ListState({ title, icon: Icon }: { title: string; icon: typeof RefreshCw }) { return <div className="flex h-60 flex-col items-center justify-center px-5 text-center"><Icon className="h-7 w-7 text-muted-foreground" /><p className="mt-3 text-sm font-medium">{title}</p></div>; }
