'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Activity, Car, LayoutDashboard, MessageCircle, Plus, Route, Search, User, Users } from 'lucide-react';
import { useAuth } from '@/components/providers/auth-provider';
import { useRoleMode } from '@/components/providers/role-mode-provider';
import { cn } from '@/lib/utils';

const passenger = [{ href: '/rides', label: 'Tìm chuyến', icon: Search }, { href: '/ride-hailing', label: 'Đặt xe', icon: Car }, { href: '/activity', label: 'Hoạt động', icon: Activity }, { href: '/messages', label: 'Tin nhắn', icon: MessageCircle }, { href: '/profile', label: 'Hồ sơ', icon: User }];
const driver = [{ href: '/driver', label: 'Tổng quan', icon: LayoutDashboard }, { href: '/rides/post', label: 'Đăng chuyến', icon: Plus }, { href: '/my-rides', label: 'Chuyến', icon: Route }, { href: '/booking-requests', label: 'Yêu cầu', icon: Users }, { href: '/messages', label: 'Tin nhắn', icon: MessageCircle }];
const admin = [{ href: '/admin', label: 'Tổng quan', icon: LayoutDashboard }, { href: '/admin/users', label: 'Người dùng', icon: Users }, { href: '/admin/rides', label: 'Carpool', icon: Route }, { href: '/admin/trips', label: 'Đặt xe', icon: Car }, { href: '/profile', label: 'Hồ sơ', icon: User }];
export function MobileBottomNav() { const { user, loading } = useAuth(); const { mode } = useRoleMode(); const pathname = usePathname(); if (loading || !user || pathname.startsWith('/messages/') || pathname.startsWith('/ride-hailing/searching') || pathname.startsWith('/ride-hailing/trip/')) return null; const items = user.role === 'ADMIN' ? admin : mode === 'driver' ? driver : passenger; return <nav aria-label="Điều hướng di động" className="fixed inset-x-0 bottom-0 z-40 border-t bg-background/95 pb-[env(safe-area-inset-bottom)] backdrop-blur-md lg:hidden"><div className="grid h-[68px] grid-cols-5">{items.map(item => { const Icon = item.icon; const active = pathname === item.href || (item.href !== '/admin' && item.href !== '/rides' && pathname.startsWith(`${item.href}/`)); return <Link key={item.href} href={item.href} aria-current={active ? 'page' : undefined} className={cn('flex min-h-[52px] flex-col items-center justify-center gap-1 px-1 text-[10px] font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring', active ? 'text-primary' : 'text-muted-foreground')}><Icon className="h-5 w-5" strokeWidth={active ? 2.5 : 2} /><span className="max-w-full truncate">{item.label}</span></Link>; })}</div></nav>; }
